import { Product } from './types'

export const PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Gosoul 2 Pro Dual Motor',
    slug: 'gosoul-2-pro',
    price: 569,
    old_price: 749,
    category: 'commuter',
    voltage: '52v',
    motor: 'dual',
    range_km: 80,
    max_speed: 60,
    weight_kg: 28,
    max_load_kg: 120,
    battery_wh: 936,
    description: 'Gosoul 2 Pro — це потужний міський самокат з подвійним мотором 2×800W. Ідеальний для тих, хто хоче більше швидкості та запасу ходу без компромісів.',
    features: ['Подвійний мотор 2×800W', 'Запас ходу 80 км', 'Максимальна швидкість 60 км/год', 'Гідравлічні гальма', 'Підсвітка 360°', 'Мобільний додаток'],
    images: ['/images/gosoul-2-pro-1.jpg', '/images/gosoul-2-pro-2.jpg'],
    in_stock: true,
    is_new: true,
    is_featured: true,
    tag: 'Новинка',
    created_at: '2026-01-01',
  },
  {
    id: '2',
    name: 'K20 Pro Dual Motor',
    slug: 'k20-pro',
    price: 529,
    old_price: 679,
    category: 'commuter',
    voltage: '48v',
    motor: 'dual',
    range_km: 65,
    max_speed: 55,
    weight_kg: 26,
    max_load_kg: 120,
    battery_wh: 768,
    description: 'K20 Pro — новинка 2026 року. Подвійний мотор, міцна рама та сучасний дизайн роблять його ідеальним вибором для міста.',
    features: ['Подвійний мотор 2×600W', 'Запас ходу 65 км', 'Швидкість 55 км/год', 'Складна конструкція', 'LED фари', 'Електронне гальмування'],
    images: ['/images/k20-pro-1.jpg'],
    in_stock: true,
    is_new: true,
    is_featured: true,
    tag: 'Новинка',
    created_at: '2026-01-15',
  },
  {
    id: '3',
    name: 'DT2 Pro E-Scooter',
    slug: 'dt2-pro',
    price: 949,
    old_price: 1029,
    category: 'offroad',
    voltage: '52v',
    motor: 'dual',
    range_km: 70,
    max_speed: 65,
    weight_kg: 34,
    max_load_kg: 150,
    battery_wh: 1066,
    description: 'DT2 Pro — позашляховий самокат преміум класу. Розроблений для бездоріжжя та екстремальних умов. Власна архітектура підвіски Ausom.',
    features: ['Мотор 2×1000W', 'Позашляхова підвіска', 'Запас ходу 70 км', 'Швидкість 65 км/год', 'Гідравлічні гальма Zoom', 'Навантаження до 150 кг'],
    images: ['/images/dt2-pro-1.jpg'],
    in_stock: true,
    is_new: false,
    is_featured: true,
    tag: 'Хіт',
    created_at: '2025-10-01',
  },
  {
    id: '4',
    name: 'F1 Max Electric Scooter',
    slug: 'f1-max',
    price: 1299,
    old_price: 1479,
    category: 'offroad',
    voltage: '60v',
    motor: 'dual',
    range_km: 90,
    max_speed: 75,
    weight_kg: 38,
    max_load_kg: 150,
    battery_wh: 1440,
    description: 'F1 Max — абсолютний флагман лінійки Ausom. 60V акумулятор, 90 км пробіг та швидкість до 75 км/год. Для тих, хто хоче найкраще.',
    features: ['Мотор 2×1500W', '60V акумулятор 1440Wh', 'Запас ходу 90 км', 'Швидкість 75 км/год', 'TFT-дисплей', 'Bluetooth + App'],
    images: ['/images/f1-max-1.jpg'],
    in_stock: true,
    is_new: false,
    is_featured: true,
    tag: 'Флагман',
    created_at: '2025-09-01',
  },
  {
    id: '5',
    name: 'SR1 Electric Scooter',
    slug: 'sr1',
    price: 759,
    old_price: 1159,
    category: 'offroad',
    voltage: '52v',
    motor: 'single',
    range_km: 75,
    max_speed: 70,
    weight_kg: 32,
    max_load_kg: 130,
    battery_wh: 1066,
    description: 'SR1 — потужний позашляховий самокат з величезною знижкою цього сезону. Надійна конструкція та вражаючі характеристики.',
    features: ['Мотор 1200W', 'Запас ходу 75 км', 'Швидкість 70 км/год', 'Пневматичні шини 10"', 'Подвійне гальмування', 'IPX4 захист'],
    images: ['/images/sr1-1.jpg'],
    in_stock: true,
    is_new: false,
    is_featured: false,
    tag: null,
    created_at: '2025-08-01',
  },
  {
    id: '6',
    name: 'L2 Max Dual Motor',
    slug: 'l2-max-dual',
    price: 749,
    old_price: 949,
    category: 'commuter',
    voltage: '48v',
    motor: 'dual',
    range_km: 85,
    max_speed: 55,
    weight_kg: 30,
    max_load_kg: 120,
    battery_wh: 960,
    description: 'L2 Max з подвійним мотором — найпопулярніша модель серії L. Чудовий баланс між міськими їздами та позашляховими можливостями.',
    features: ['Подвійний мотор 2×800W', 'Запас ходу 85 км', 'Швидкість 55 км/год', 'Пневматичні шини', 'Передня вилочна підвіска', 'Складна конструкція'],
    images: ['/images/l2-max-dual-1.jpg'],
    in_stock: true,
    is_new: false,
    is_featured: true,
    tag: null,
    created_at: '2025-07-01',
  },
  {
    id: '7',
    name: 'L1 Electric Scooter',
    slug: 'l1',
    price: 499,
    old_price: 629,
    category: 'commuter',
    voltage: '48v',
    motor: 'single',
    range_km: 50,
    max_speed: 45,
    weight_kg: 20,
    max_load_kg: 100,
    battery_wh: 468,
    description: 'L1 — ідеальний старт у світ Ausom. Легкий, надійний та доступний міський самокат для щоденних поїздок.',
    features: ['Мотор 500W', 'Запас ходу 50 км', 'Швидкість 45 км/год', 'Вага лише 20 кг', 'Складний за 3 секунди', 'Підходить для початківців'],
    images: ['/images/l1-1.jpg'],
    in_stock: true,
    is_new: false,
    is_featured: false,
    tag: null,
    created_at: '2025-06-01',
  },
  {
    id: '8',
    name: 'Gosoul 2',
    slug: 'gosoul-2',
    price: 499,
    old_price: 699,
    category: 'commuter',
    voltage: '48v',
    motor: 'single',
    range_km: 60,
    max_speed: 50,
    weight_kg: 22,
    max_load_kg: 110,
    battery_wh: 614,
    description: 'Gosoul 2 — оновлена версія популярного міського самоката. Більше запасу ходу, покращена підвіска та стильний дизайн.',
    features: ['Мотор 800W', 'Запас ходу 60 км', 'Швидкість 50 км/год', 'Оновлена підвіска', 'USB зарядка', 'Круїз-контроль'],
    images: ['/images/gosoul-2-1.jpg'],
    in_stock: true,
    is_new: false,
    is_featured: false,
    tag: null,
    created_at: '2025-11-01',
  },
]

export function getProductBySlug(slug: string): Product | undefined {
  return PRODUCTS.find(p => p.slug === slug)
}

export function getFeaturedProducts(): Product[] {
  return PRODUCTS.filter(p => p.is_featured)
}

export function getProductsByCategory(category: string): Product[] {
  if (category === 'all') return PRODUCTS
  if (category === 'new') return PRODUCTS.filter(p => p.is_new)
  if (category === 'offroad') return PRODUCTS.filter(p => p.category === 'offroad')
  if (category === 'commuter') return PRODUCTS.filter(p => p.category === 'commuter')
  return PRODUCTS
}
